from uuid import UUID

from models.utils import Message


class Packet:
    """
    Packet format for the stop-and-wait UDP file transfer protocol.

    Fields
    ------
    connection_id  : UUID   - random ID generated by client; tags every packet of a transfer
    seq_num        : int    - alternating 0/1 for stop-and-wait
    msg_type       : Message - REQUEST | DATA | ACK | ERROR
    payload_length : int    - byte length of payload (auto-computed when omitted)
    final          : bool   - True on the last DATA packet of a transfer
    payload        : any    - filename dict (REQUEST), bytes (DATA), None (ACK), str (ERROR)
    """

    def __init__(
        self,
        connection_id: UUID,
        seq_num: int,
        msg_type: Message,
        payload,
        payload_length: int = None,
        final: bool = False,
    ):
        self.connection_id = connection_id
        self.seq_num = seq_num
        self.msg_type = msg_type
        self.final = final
        self.payload = payload

        # Auto-compute payload_length when not supplied
        if payload_length is not None:
            self.payload_length = payload_length
        elif payload is None:
            self.payload_length = 0
        elif isinstance(payload, (bytes, bytearray)):
            self.payload_length = len(payload)
        elif isinstance(payload, str):
            self.payload_length = len(payload.encode())
        elif isinstance(payload, dict):
            # REQUEST payload: {"filename": ..., "max_payload": ...}
            fname = payload.get("filename", "")
            self.payload_length = len(fname.encode() if isinstance(fname, str) else fname)
        else:
            self.payload_length = 0

    def __repr__(self) -> str:
        cid = str(self.connection_id)[:8]
        return (
            f"Packet(conn={cid}…, seq={self.seq_num}, "
            f"type={self.msg_type}, len={self.payload_length}, final={self.final})"
        )